language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script: composer install --dev

script: phpunit --coverage-clover clover

matrix:
  allow_failures:
    - php: hhvm

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php

